[package]
name = "clipsynk"
version = "0.1.0"
edition = "2024"

[workspace]
members = [".", "clipsynk-core"]


[workspace.dependencies]
tokio = { version = "1.53.1", features = ["full"] }
uuid = { version = "1.24.0", features = ["v4", "serde"] }



[dependencies]
clipsynk-core = {path="./clipsynk-core", version = "0.1.0"}
tokio.workspace = true
uuid.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
wayland-clipboard-listener = "0.6.1"
wl-clipboard-rs = "0.9.3"
clipboard-master = "4.0.0"
arboard = "3.6.1"

[target.'cfg(target_os = "windows")'.dependencies]
clipboard-master = "4.0.0"
clipboard-win = "5.4.1"

[target.'cfg(target_os = "macos")'.dependencies]
clipboard-master = "4.0.0"
arboard = "3.6.1"
