[package]
name = "clipsynk"
version = "0.1.0"
edition = "2024"

[dependencies]
local-ip-address = "0.6.13"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["full"] }
xxhash-rust = { version = "0.8.18", features = ["const_xxh3"] }

[target.'cfg(target_os = "linux")'.dependencies]
wayland-clipboard-listener = "0.6.1"
wl-clipboard-rs = "0.9.3"

[target.'cfg(target_os = "windows")'.dependencies]
clipboard-master = "4.0.0"
clipboard-win = "5.4.1"

[target.'cfg(target_os = "macos")'.dependencies]
clipboard-master = "4.0.0"
arboard = "3.6.1"
