[package]
name = "clipsynk"
version = "0.1.8"
edition = "2024"

[workspace]
members = [".", "clipsynk-core"]


[workspace.dependencies]
tokio = { version = "1.53.1", features = ["full"] }
uuid = { version = "1.24.0", features = ["v4", "serde"] }



[dependencies]
clipsynk-core = {path="./clipsynk-core", version = "0.1.0"}
tokio.workspace = true
uuid.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
wayland-clipboard-listener = "0.6.1"
wl-clipboard-rs = "0.9.3"
clipboard-master = "4.0.0"
arboard = "3.6.1"

[target.'cfg(target_os = "windows")'.dependencies]
clipboard-master = "4.0.0"
clipboard-win = "5.4.1"

[target.'cfg(target_os = "macos")'.dependencies]
clipboard-master = "4.0.0"
arboard = "3.6.1"

[package.metadata.deb]
maintainer = "Parvez Ali <parvez@clipsynk.io>"
copyright = "2026, Parvez Ali"
extended-description = "Seamless peer-to-peer LAN clipboard synchronizer daemon between Linux, Windows, and Android."
section = "net"
priority = "optional"
assets = [
    ["target/release/clipsynk", "usr/bin/clipsynk", "755"],
    ["distribution/linux/clipsynk.service", "usr/lib/systemd/user/clipsynk.service", "644"]
]

[package.metadata.generate-rpm]
summary = "Seamless peer-to-peer LAN clipboard synchronizer daemon"
description = "ClipSynk synchronizes your clipboard in real-time across your local network between Linux, Windows, and Android."
license = "MIT OR Apache-2.0"
assets = [
    { source = "target/release/clipsynk", dest = "/usr/bin/clipsynk", mode = "755" },
    { source = "distribution/linux/clipsynk.service", dest = "/usr/lib/systemd/user/clipsynk.service", mode = "644" }
]
