[package]
name = "clipsynk-core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = "Cross-device real-time clipboard sync over your local network"

[dependencies]
local-ip-address.workspace = true
serde.workspace = true
serde_json.workspace = true
socket2.workspace = true
thiserror.workspace = true
tokio.workspace = true
uuid.workspace = true
xxhash-rust.workspace = true
