[package]
name = "clipsynk-desktop"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Cross device real-time light-weight clipboard sync over your local network"

[[bin]]
name = "clipsynk"
path = "src/main.rs"

[dependencies]
clipsynk-core = { path = "../clipsynk-core", version = "0.1.2" }
tokio.workspace = true
uuid.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
wayland-clipboard-listener = "0.6.1"
wl-clipboard-rs = "0.9.3"
clipboard-master = "4.0.0"
arboard = "3.6.1"

[target.'cfg(target_os = "windows")'.dependencies]
clipboard-master = "4.0.0"
clipboard-win = "5.4.1"

[target.'cfg(target_os = "macos")'.dependencies]
clipboard-master = "4.0.0"
arboard = "3.6.1"
